name: TMT
description: Trouble in MineTown
main: me.turkey2349.plugin.TMT
version: 1.0.3
author: Turkey2349
commands:
   Join:
       description: Lets the player join the game
       usage: /TMT <command>
   Leave:
      description: Lets the player leave the game
      usage: /TMT <command>
   ForceStart:
      description: Lets the player FoceStart the game
      usage: /TMT <command>