name: TMT
description: Trouble in MineTown
main: me.turkey2349.plugin.TMT
version: Beta V3
author: [Turkey2349]
authors: [teh_jombi]
commands:
   TMTjoin:
       description: Lets the player join the game
       permission: TMT.Join
       permission-message: You don't have <permission>
   TMTleave:
      description: Lets the player leave the game
      permission: TMT.Leave
      permission-message: You don't have <permission>
   TMTreset:
      description: resets the game
      permission: TMT.Reset
      permission-message: You don't have <permission>
   TMTfs:
      description: Lets the player FoceStart the game
      permission: TMT.ForceStart
      permission-message: You don't have <permission>
   TMTcreate:
      description: Lets the player Create an arena
      permission: TMT.Create
      permission-message: You don't have <permission>
   TMTArenaSpawn:
      description: Lets the player Assign the Arena spawn
      permission: TMT.ArenaSpawn
      permission-message: You don't have <permission>
   TMTVeto:
      description: Lets the player veto a map
      permission: TMT.Veto
      permission-message: You don't have <permission>
   TMTSkip:
      description: Lets the player Skip the Map
      permission: TMT.Skip
      permission-message: You don't have <permission>
   TMTFly:
      description: Lets the player Fly When Dead
      permission: TMT.Fly
      permission-message: You don't have <permission>
   TMTArenas:
      description: Lets the player see all created arenas
      permission: TMT.Arenas
      permission-message: You don't have <permission>
