name: TMT
description: Trouble in MineTown
main: me.turkey2349.plugin.TMT
version: 1.0.3
author: Turkey2349
authors: [teh_jombi]
commands:
   TJoin:
       description: Lets the player join the game
       usage: Syntax error! /<command>
   TLeave:
      description: Lets the player leave the game
      usage: Syntax error! /<command>
   TFS:
      description: Lets the player FoceStart the game
      usage: Syntax error! /<command>