name: TMT
description: Trouble in MineTown
main: me.turkey2349.plugin.TMT
version: 1.0.3
author: Turkey2349
authors: [teh_jombi]
commands:
   TMTjoin:
       description: Lets the player join the game
       usage: /<command>
   TMTleave:
      description: Lets the player leave the game
      usage: /<command>
   TMTfs:
      description: Lets the player FoceStart the game
      usage: /<command>
   TMTcreate:
      description: Lets the player Create an arena
      usage: /<command> <arenaName>
   TMTas:
      description: Lets the player Assign the Arena spawn
      usage: /<command> <exsistingArenaName>