name: TMT
description: Trouble in MineTown
main: me.turkey2349.plugin.TMT
version: 1.0.1b
author: Turkey2349
commands:
   TMT Join:
      description: Lets the player join the game
      usage: /TMT <command>
   TMT Leave:
      description: Lets the player leave the game
      usage: /TMT <command>
   TMT ForceStart:
      description: Lets the player FoceStart the game
      usage: /TMT <command>